### ISSUE TITLE
Move pass invocation into `codepropertygraph`

### ISSUE THREAD

**Issue by fabsx00** [joernio/javasrc2cpg#31]
Not urgent: passes beyond CFG creation should be run as part of SCPG layer creation by adding a case here:

https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/semanticcpg/src/main/scala/io/shiftleft/semanticcpg/layers/Scpg.scala#L54

That way, for setups where initial CPGs are created on a low-end machine and sent to the cloud, most of the computation is delayed to be performed in the cloud. This is mostly relevant for ngsast.

**Comment by johannescoetzee** [comment]
Added in https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1462 and https://github.com/joernio/javasrc2cpg/pull/34
